name: Build for Nuvoton NUC972

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    - name: Load Default Configuration
      run: make nuvoton_nuc972_defconfig

    - name: Run Make
      run: make

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-files
        path: output/images
