name: Build for Nuvoton NUC972

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore cached dl folder
        uses: actions/cache@v3
        id: restore_cache
        with:
          path: dl
          key: ${{ runner.os }}-dl-${{ hashFiles('dl/**') }}

      - name: Setup Build Environment
        run: |
          sudo apt-get install -y gcc make

      - name: Load Default Configuration
        run: make nuvoton_nuc970_defconfig

      - name: Run Make
        run: make

      - name: Cache dl folder
        uses: actions/cache@v3
        with:
          path: dl
          key: ${{ runner.os }}-dl-${{ hashFiles('dl/**') }}

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-files
          path: output/images
